server:
  namespace: temporal-system
  additionalHeaders:
    X-Cluster: tribalmingle
  config:
    persistence:
      defaultStore:
        driver: cassandra
      visibilityStore:
        driver: cassandra
  metrics:
    prometheus:
      enabled: true
  pods:
    annotations:
      linkerd.io/inject: enabled

web:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - host: temporal.tribalmingle.local
        paths:
          - /

worker:
  enabled: true

cassandra:
  enabled: true
  config:
    cluster_size: 3
    cluster_domain: cassandra
