apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tribalmingle/tribalmingle
    targetRevision: main
    path: infra/k8s/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
