apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jobs
resources:
  - deployment-bullmq.yaml
  - cronjob-funnel-snapshot.yaml
commonLabels:
  app.kubernetes.io/part-of: jobs-stack
