apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - platform-gateway.yaml
  - graphql-configmap.yaml
  - platform-gateway-canary-service.yaml
  - router-configmap.yaml
